---
title: "TidyTuesday 2020 Week 43"
author: "Kaustav Sen"
date: "10/24/2020"
output: 
  html_document:
    theme: journal
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE, include = FALSE, warning = FALSE, error = FALSE, message = FALSE)
```

```{r load-packages}
library(tidyverse)
library(gt)
library(showtext)
library(tidytuesdayR)
```

```{r get-data}
# tuesdata <- tt_load(2020, 43)
# beer_awards <- tuesdata$beer_awards

beer_awards <- readr::read_csv('https://raw.githubusercontent.com/rfordatascience/tidytuesday/master/data/2020/2020-10-20/beer_awards.csv')
```

```{r wrangle}
top_10_breweries <- 
  beer_awards %>% 
  group_by(brewery, medal) %>% 
  select(brewery, medal) %>% 
  summarise(num = n()) %>% 
  ungroup() %>% 
  pivot_wider(names_from = medal, values_from = num) %>% 
  arrange(-Gold) %>% 
  head(10)
```

```{r barchart-function}
plot_barchart <- function(brewery, data) {
  
  plot_data <- 
    beer_awards %>% 
    filter(brewery == {{ brewery }}) %>% 
    count(year)

  plot <- 
    plot_data %>% 
    ggplot(aes(year, n)) +
    geom_col(fill = "#F28705", alpha = 0.75) +
    geom_segment(aes(x = 1986.5, xend = 1986.5, y = -0.1, yend = -0.5)) +
    geom_segment(aes(x = 2020.5, xend = 2020.5, y = -0.1, yend = -0.5)) +
    geom_segment(aes(x = 1986.5, xend = 2020.5, y = -0.1, yend = -0.1)) +
    annotate("text", x = 1986.5, y = -1.25, label = "1987", family = "IBM Plex Mono", size = 10, color = "grey40") +
    annotate("text", x = 2020.5, y = -1.25, label = "2020", family = "IBM Plex Mono", size = 10, color = "grey40") +
    scale_x_continuous(limits = c(1970, 2035)) +
    scale_y_continuous(limits = c(-4, 10)) +
    theme_void()    
    
  plot
  
}
```

```{r gt-table, include=TRUE}
table_data <- 
  top_10_breweries %>% 
  select(brewery, Gold, Silver, Bronze) %>% 
  mutate(plots = map(brewery, plot_barchart, data = beer_awards))  
  
gt_table <- 
  gt(table_data) %>% 
  cols_label(
    brewery = "",
    Gold = emo::ji("1st_place_medal"),
    Silver = emo::ji("2nd_place_medal"),
    Bronze = emo::ji("3rd_place_medal"),
    plots = md("**Medal Distribution<br>1987-2020**")
  ) %>% 
  tab_header(
    title = "Great   American   Beer   Festival",
    subtitle = html("<span style = 'color: grey'>All time top 10 breweries of which 2 are <span style = 'color: #F2CB05'><b>California</b></span> based</span>")
  ) %>% 
  tab_style(
    style = cell_text(font = google_font("Titan One"), align = "left", size = "xx-large"),
    locations = cells_title("title")
  ) %>% 
  tab_style(
    style = cell_text(font = google_font("IBM Plex Sans"), align = "left", size = "large"),
    locations = cells_title("subtitle")
  ) %>% 
  tab_style(
    style = cell_borders(sides = "bottom", color = "#ebe8e8", weight = px(2)),
    locations = cells_title("subtitle")
  ) %>% 
  text_transform(
    locations = cells_body(vars(plots)),
    fn = function(x) {
      map(table_data$plots, ggplot_image, height = px(120), aspect_ratio = 1.5)
    }
  ) %>% 
  tab_spanner(
    label = "Medals Won",
    columns = 2:4
  ) %>% 
  tab_style(
    style = cell_text(font = google_font("IBM Plex Sans"), size = "large"),
    locations = list(cells_column_labels(everything()), cells_body(columns = 1))
  ) %>%  
  tab_style(
    style = cell_text(font = google_font("IBM Plex Sans"), size = "medium", weight = "bold"),
    locations = cells_column_spanners("Medals Won")
  ) %>% 
  tab_style(
    style = cell_text(font = google_font("IBM Plex Mono"), size = "large"),
    locations = cells_body(columns = 2:4)
  ) %>% 
  tab_style(
    style = cell_text(color = "#F2CB05", weight = "bold"),
    locations = cells_body(columns = 1, rows = brewery %in% c("Firestone Walker Brewing Co.", "Marin Brewing Co."))
  ) %>% 
  cols_width(
    1 ~ px(300),
    2:4 ~ px(50)
  ) %>% 
  tab_source_note(md("**Data**: Great American Beer Festival | **Table**: Kaustav Sen")) %>% 
  tab_options(
    column_labels.border.top.color = "white",
    column_labels.border.bottom.color = "black",
    table.border.top.color = "white",
    table.border.bottom.color = "white",
    table_body.hlines.color = "white"
  )

gt_table
```

```{r table-save}
path <- here::here(2020, "plots", "week_43.")
pdftools::pdf_convert(paste0(path, "pdf"), filenames = paste0(path, ".png"), dpi = 300)
```

