---
title: 'Avatar: the last airbender'
author: "Kaustav Sen"
date: "11/08/2020"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r load-libraries}
library(tidyverse)
library(tvthemes)
library(ggnewscale)
library(extrafont)
library(tidytuesdayR)

loadfonts(device = "win")
```

```{r load-data}
tuesdata <- tidytuesdayR::tt_load(2020, week = 33)
tuesdata

avatar <- tuesdata$avatar
```

```{r generate-plot}
font <- "Slayer"

mean_ratings_by_book <- 
  avatar %>% 
  mutate(book = fct_inorder(book)) %>% 
  group_by(book) %>% 
  summarise(imdb_rating = mean(imdb_rating, na.rm = TRUE)) %>% 
  mutate(book_num = as.numeric(book))

avatar %>% 
  mutate(book = fct_inorder(book)) %>% 
  filter(!is.na(imdb_rating)) %>% 
  ggplot(aes(book, imdb_rating)) +
  geom_line(data = mean_ratings_by_book,
            group = 1,
            size = 2,
            color = "#c7c45e",
            alpha = 0.4) +
  geom_jitter(aes(color = chapter_num), width = 0.1, height = 0.1, alpha = 1/20) +
  geom_point(data = mean_ratings_by_book, 
             size = 4,
             color = "#572530",
             alpha = 0.5) +
  scale_y_continuous(limits = c(6, NA),
                     breaks = seq(6, 10, 1)) +
  scale_color_gradient(name = "",
                       low = "#c7c45e", high = "#4c7022",
                       breaks = c(3, 19),
                       labels = c("Initial \nChapters", "Later \nChapters")) +
  new_scale("color") +
  geom_text(data = mean_ratings_by_book,
            aes(y = 6,
                color = factor(book_num),
                label = book),
            angle = 90,
            vjust = 0.5,
            hjust = 0,
            size = 5,
            alpha = 0.5,
            family = font) +
  scale_color_manual(guide = FALSE,
                     values = c("1" = "#0047ab", "2" = "#015E05", "3" = "#a10000")) +
  coord_equal(ratio = 0.75) +
  labs(title = "Avatar: The Last Airbender",
       subtitle = "How do the ratings change as we \nprogress through the chapters?",
       x = "",
       y = "IMDB Rating") +
  theme_avatar() +
  theme(legend.background = element_blank(),
        plot.title.position = "plot",
        plot.title = element_text(family = font,
                                  face = "bold",
                                  hjust = 0.5),
        plot.subtitle = element_text(family = font,
                                  hjust = 0.5,
                                  margin = margin(b = 10)),
        panel.grid.major.x = element_blank(),
        axis.text.x = element_blank(),
        axis.title.y = element_text(family = font,
                                    margin = margin(r = 10)),
        axis.text.y = element_text(family = font),
        legend.box.margin = margin(b = 30),
        legend.text = element_text(family = font,
                                   size = 6),
        panel.grid.major.y = element_line(linetype = "dashed",
                                    size = 0.5,
                                    color = "#c7c45e"),
        panel.grid.minor.y = element_line(linetype = "dashed",
                                    size = 0.5,
                                    color = "#c7c45e")) +
  ggsave("plots/week_33.png", height = 8, width = 8, type = "cairo")
```

```{r}
scales::show_col(avatar_pal("EarthKingdom")(7))
```

